### ISSUE TITLE
NavSatFix coordinates to the detected object

### ISSUE THREAD

**Issue by aegan148** [Pigwomaniak/tree_seeker#1]
Hello! Can you please help me in follow issue?
"localizeObjects() "- here you got an information about detected object. I really interested, can I calculate the GPS coordinates to the detected object?

**Comment by Pigwomaniak** [comment]
Yes, you can. The `objectGlobalPosition` has the longitude and latitude parameter already build in.

**Comment by aegan148** [comment]
wow, now i see it, good job! 
I'm new in this field, I want to understand some things for my similar scientific project and get understanding how fit it to me . If you don't mind I ask you also few questions?)
1. How did you found out the "CAMERA_X_ANGLE", "CAMERA_Y_ANGLE" define? how can i find it in my camera? 
2. MERES_TO_LATITUDE?
3. When you get "objectGlobalPosition.longitude =".... I misunderstood that is the number "40075000" and "M_PI"?

**Comment by aegan148** [comment]
I suppose that I've a static drone camera which just looking 30 degrees relative to the axis of the drone and detecting objects. In the very beginning I just want to get coordinates to the detected object...
